version: '3.8'

services:
  springbootapp:
    image: adoptopenjdk/openjdk17:alpine-jre
    container_name: springbootapp
    ports:
      - "8080:8080"
    volumes:
      - ./target:/app
    working_dir: /app
    command: ["java", "-jar", "sua-aplicacao-spring-boot.jar"]
